### ISSUE TITLE
Initial research

### ISSUE THREAD

**Issue by krutarth4** [Smoothex/parking-place-occupancy#1]
- [ ] Research for the data available for open source parking space in the vicinity of Berlin.

- [ ] look for available solutions regarding the same space visualization.

**Comment by Smoothex** [comment]
We should talk about the data structure. Since we'll be working with map coordinates, we need a data structure suitable for geographical search.
Some options for a data structure:
* [QuadTree](https://en.wikipedia.org/wiki/Quadtree) - this is an [example of Java QuadTree Implementation](https://algs4.cs.princeton.edu/92search/QuadTree.java.html). Here's a good [YouTube video](https://youtu.be/UaMzra18TD8?si=889n62w5wEHKWTIy) about it.
* [Geohashes](https://www.ibm.com/docs/en/streams/4.3.0?topic=334-geohashes)- explained pretty good in this [YouTube video](https://youtu.be/FZHK05JV-tU?si=i7Hgf2u8cfg4xyFr).
* [B-Tree](https://en.wikipedia.org/wiki/B-tree) ([YouTube](https://youtu.be/FgWbADOG44s?si=lnCUW7VMpQgZNnj3) video about it) - it seems to be designed for rather large volumes of data. This isn't suitable for us, because we'll be working with data from Berlin. 
* [R-Tree](https://en.wikipedia.org/wiki/R-tree) - I found [this YouTube video](https://youtu.be/EnNlqReOeSA?si=1AodHaxThIuGovp9). It seems like Graphileon has a [free tier](https://graphileon.com/licenses/), we'll need to see if it would fit out needs if we decide to go for R-Tree.

For manipulating the geometric shapes, we can look into using something like the [S2 library](s2geometry.io). It's from Google and also has a [Java implementation](https://github.com/google/s2-geometry-library-java). This might be relevant for editing the parking spaces (but we also need to discuss how we want to edit them).

**Comment by Smoothex** [comment]
[This YouTube video](https://youtu.be/7IUBABSWgcE?si=eZ4BMVIqlhz50_Gl) covers handling geolocation in PostgreSQL with PostGIS really well. It shows how to get PostgreSQL up and running and how to add the PostGIS extension. From what it seems like, we'll do something very close to this, but we'll create the database schema according to our use case.

And then for connecting to the DB, we'll need the Java [PostgreSQL JDBC Driver](https://jdbc.postgresql.org/).

**Comment by krutarth4** [comment]
### Map functionalities :

- Open street map does’t provide aerial maps/satellite map views
- Alternative :openAerialMap // http://openaerialmap.org/?zoom=13&lat=47.81396&lon=7.55947&layers=BT
    - Google maps but funds will not be provided for Google API usage

**Comment by krutarth4** [comment]
### Parking space:

- Parking spaces marked in open street maps:


<img width="514" alt="Screenshot 2023-10-30 at 13 47 32" src="https://github.com/Smoothex/parking-place-occupancy/assets/74930393/3f0245dc-0925-458d-94b0-eba0c82a752c">

- This is do-able but manual labor work
    
<img width="1261" alt="Screenshot 2023-10-30 at 13 16 36" src="https://github.com/Smoothex/parking-place-occupancy/assets/74930393/23ab2e00-8d16-4684-bf43-1731c0dcf2a3">



Also support such rendering of data :

But not available in Berlin 


<img width="1015" alt="Screenshot 2023-10-30 at 14 13 25" src="https://github.com/Smoothex/parking-place-occupancy/assets/74930393/16a1b8e4-cf6e-4e43-84de-053ffe464d0f">


The parking space split can be handled using a plugin https://github.com/JOSM/josm-gridify

**Comment by Smoothex** [comment]
The Gridify extension is a nice find @krutarth4 :)

I looked into the data sctructures a bit more and my first thoughts are that Geohash might not be our best choice. It seems to be good for finding points in areas, but since we'll be working with polygons which may be irregulary shaped, R-Tree looks like a better fit. You can see how the irregularly shaped building objects were shown in the video I sent in my previous comment about R-Trees. PostGIS also comes with an [implementation of R-Tree for spatial indexing](http://postgis.net/documentation/faq/spatial-indexes/).

**Comment by krutarth4** [comment]
Also, @gogokotsev00  @Smoothex  if you guys find data about parking spaces in Berlin. I tried to look at FIS broker berlin, but they only have data available about the regions and how much it cost to park there. Furthermore, some data regarding the Handicapped parking space is available but not for parking space.

**Comment by Smoothex** [comment]
@krutarth4 what about this: [Straßenbefahrung 2014 - Parkfläche](https://daten.berlin.de/datensaetze/stra%C3%9Fenbefahrung-2014-parkfl%C3%A4che-wfs)? This links to the [FIS Broker Dataset](https://fbinter.stadt-berlin.de/fb/?loginkey=alphaDataStart&alphaDataId=s_Parkflaeche@senstadt). That's the same dataset used by the [Parkraumkartierung EUVM](https://www.berlin.de/sen/uvk/_assets/verkehr/verkehrspolitik/forschungs-und-entwicklungsprojekte/parkraumkartierung_euvm.pdf).

**Comment by gogokotsev00** [comment]
- I also took a look at what you've discussed and think that we can use the data structure like this waypoint object in [OSRM API](https://project-osrm.org/docs/v5.24.0/api/?language=cURL#waypoint-object), but adjusted to our objects (parking spots). 
- In PostgreSQL we'll have to enable the PostGIS extension, which provides Polygon data types and makes our work with them easier.
- Regarding the dataset, I believe the FIS Broker one is the only accurate mapping we have and also our project supervisor send us datasets, which in my opinion also come from it.
- Probably we could make also use of the Gridify plugin, but am not sure if the scope of time and effort is achievable until our deadline.
- Still, we have to analyze further how to separate the spots from each other.

**Comment by Smoothex** [comment]
@gogokotsev00 I don't think we can use a Waypoint object, because as the documentation says, it's a  _waypoint on a route_. OSRM stands for Open Source **Routing** Machine, it's a routing engine and I don't think we'll be doing any routing in this project.

**Comment by Smoothex** [comment]
Closing as we already have an idea of what the project looks like and how to go about it.
